name: heroku_deploy
on: 
  push:                           
    branches:
      - master
      - main
jobs:                        
  build:                          
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2        
       - uses: akhileshns/heroku-deploy@v3.6.8
         with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: "puzzlemath"
           heroku_email: ${{secrets.HEROKU_EMAIL}}
           usedocker: true
           docker_build_args: |
            GH_PAT
           env:
            GH_PAT: ${{ secrets.GH_TOKEN }}
